/**
 * Placeholder resume download. Replace by dropping a real CV at
 * `public/resume.pdf` and updating the button hrefs in
 * `components/sections/AboutHero.tsx` and `components/sections/ResumeCTA.tsx`
 * back to `/resume.pdf`.
 */
export async function GET() {
  const body = `EMAD — RESUME (placeholder)

This is a placeholder file served by /api/resume. To replace it with the real CV:

  1. Drop your CV PDF at  public/resume.pdf
  2. Open  components/sections/AboutHero.tsx  and change href="/api/resume"
     back to href="/resume.pdf"
  3. Do the same in  components/sections/ResumeCTA.tsx

Generated by the portfolio scaffold.
`;
  return new Response(body, {
    status: 200,
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Content-Disposition':
        'attachment; filename="emad-resume-placeholder.txt"',
      'Cache-Control': 'no-store',
    },
  });
}
