import { setRequestLocale } from 'next-intl/server';

export const metadata = {
  title: 'Terms of Service — emadai.dev',
  robots: { index: true, follow: true },
};

export default async function TermsPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);
  const updated = '22 May 2026';

  return (
    <div className="container py-12 md:py-16">
      <div className="mx-auto max-w-3xl prose prose-neutral dark:prose-invert">
        <h1>Terms of Service</h1>
        <p className="text-sm text-muted-foreground">Last updated: {updated}</p>

        <h2>1. Acceptance</h2>
        <p>
          By creating an account or using any service on <strong>emadai.dev</strong>, you agree to
          these Terms. If you do not agree, do not use the site.
        </p>

        <h2>2. Services provided</h2>
        <p>
          emadai.dev offers AI consulting, software development, automation tools, and related
          digital services. Some services are delivered automatically (AI-generated outputs);
          others are fulfilled manually by the site owner.
        </p>

        <h2>3. Free tier and payments</h2>
        <ul>
          <li>Certain features are available free of charge with limited output (demo tier).</li>
          <li>Full service delivery requires payment as indicated on the service page.</li>
          <li>Prices are in EUR and include Romanian VAT where applicable.</li>
          <li>Payments are processed by Stripe. By paying, you also agree to <a href="https://stripe.com/legal/end-users" target="_blank" rel="noopener noreferrer">Stripe&apos;s terms</a>.</li>
          <li>Refunds are handled case by case — contact us within 14 days of purchase.</li>
        </ul>

        <h2>4. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Create multiple accounts to abuse the free tier.</li>
          <li>Submit false, misleading, or harmful content through service request forms.</li>
          <li>Attempt to circumvent rate limits, authentication, or security controls.</li>
          <li>Use AI-generated outputs for illegal purposes or to harm others.</li>
          <li>Reverse-engineer or scrape the platform.</li>
        </ul>

        <h2>5. AI-generated content</h2>
        <ul>
          <li>Automated service outputs (chatbot configs, travel options, embed code) are generated by AI and provided as-is.</li>
          <li>We do not guarantee accuracy, fitness for purpose, or completeness of AI outputs.</li>
          <li>You are responsible for reviewing and testing any AI-generated content before deploying it.</li>
          <li>Travel links point to third-party booking platforms — we are not responsible for their availability or pricing.</li>
        </ul>

        <h2>6. Intellectual property</h2>
        <p>
          AI-generated outputs delivered to you as part of a paid service are yours to use commercially.
          The platform code, design, and brand remain the property of the site owner.
        </p>

        <h2>7. Limitation of liability</h2>
        <p>
          To the maximum extent permitted by Romanian and EU law, our liability for any claim
          arising from use of this service is limited to the amount you paid for the specific
          service in question. We are not liable for indirect, incidental, or consequential damages.
        </p>

        <h2>8. Governing law</h2>
        <p>
          These Terms are governed by the laws of Romania. Any disputes shall be resolved in the
          courts of Baia Mare, Romania, unless mandatory consumer protection laws in your country
          provide otherwise.
        </p>

        <h2>9. Contact</h2>
        <p>
          Questions? Email <a href="mailto:hamidleo1984@gmail.com">hamidleo1984@gmail.com</a>
        </p>
      </div>
    </div>
  );
}
